# Data Preprocessing
1. Data Splitting
2. Handle Missing Values
3. Feature Encoding
4. Feature Selection

In [1]:
import pandas as pd

## Data Splitting

In [2]:
from sklearn.model_selection import train_test_split
df = pd.read_csv('../data/heart-disease.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
# Features (X) and Labels (y) Split
X = df.drop('target', axis=1)
y = df['target']

In [5]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Handle Missing Values

In [ ]:
from sklearn.compose import ColumnTransformer
df = pd.read_csv('../data/car-sales-extended-missing-data.csv')

In [7]:
df.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [8]:
# Cek Missing Values
df.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [9]:
# Hapus kolom target yang ada missing values
df.dropna(subset='Price', inplace=True)

In [10]:
df.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [ ]:
# Data Splitting
X = df.drop('Price', axis=1)
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [25]:
X_train.head()

       Make Colour  Odometer (KM)  Doors
736  Toyota  White       129188.0    4.0
626  Nissan  White       235952.0    4.0
847   Honda  Green            NaN    4.0
385   Honda    NaN        89291.0    4.0
386  Nissan   Blue        18044.0    3.0

In [ ]:
# Handle Missing Values
from sklearn.impute import SimpleImputer
# apa yang bakal dilakuin untuk tiap jenis kolom
cat_imputer = SimpleImputer(strategy='constant', fill_value='missing') # Category = 'missing'
num_imputer = SimpleImputer(strategy='mean') # Numerik = nilai mean kolom
door_imputer = SimpleImputer(strategy='constant', fill_value=4) # Kolom Doors = 4 pintu di mobil umumnya 4

# misahin kolom yang bakal di-impute
cat_feat = ['Make', 'Colour']
num_feat = ['Odometer (KM)']
door_feat = ['Doors']

# gabung semua imputer
imputer = ColumnTransformer([
    ('cat_imputer', cat_imputer, cat_feat),
    ('num_imputer', num_imputer, num_feat),
    ('door_imputer', door_imputer, door_feat)
])

# fill missing values
filled_X_train = imputer.fit_transform(X_train)
filled_X_test = imputer.transform(X_test)

In [13]:
# ubah supaya jadi DataFrame
x_train = pd.DataFrame(filled_X_train, columns=X_train.columns)
x_test = pd.DataFrame(filled_X_test, columns=X_test.columns)

In [23]:
x_train.head()

     Make   Colour  Odometer (KM) Doors
0  Toyota    White       129188.0   4.0
1  Nissan    White       235952.0   4.0
2   Honda    Green  131592.698061   4.0
3   Honda  missing        89291.0   4.0
4  Nissan     Blue        18044.0   3.0

In [24]:
x_test.head()

      Make Colour Odometer (KM) Doors
0   Toyota  White      108569.0   4.0
1   Toyota  White       10247.0   4.0
2   Toyota  White      185742.0   4.0
3  missing  White      128072.0   4.0
4    Honda   Blue      163297.0   4.0

In [22]:
x_train.isna().sum(), x_test.isna().sum()

(Make             0
 Colour           0
 Odometer (KM)    0
 Doors            0
 dtype: int64,
 Make             0
 Colour           0
 Odometer (KM)    0
 Doors            0
 dtype: int64)

## Feature Encoding

In [ ]:
# Opsi 1: encoding doang
from sklearn.preprocessing import OneHotEncoder
# pilih kolom yang mau di-encoding
categorical_features = ['Make', 'Colour', 'Doors']
# membuat transformer
one_hot = OneHotEncoder()
transformer = ColumnTransformer(
    [('one_hot', one_hot, categorical_features)],
    remainder='passthrough'
)
# encoding
X_train_encoded = transformer.fit_transform(x_train)
X_test_encoded = transformer.transform(x_test)